version: '2.17.3'
services:
  app:
    image: mhlreis/dockerflask:v2.0
    container_name: flask-mysql_flask
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: flask-mysql_mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=F@tec123
      - MYSQL_DATABASE=devweb
    volumes:
      - /var/lib/mysql:/var/lib/mysql